name: "dts-sample-action"
author: "chaya2z"
description: "Sample GitHub Action with Deno"
inputs:
  token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
    required: false
  allow-net:
    description: |
      Allow network access
      You can specify a comma-separated list
    required: false
  allow-env:
    description: |
      Allow environment variables access
      You can specify a comma-separated list
    required: false
runs:
  using: composite
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Deno Run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: >
        deno run
        ${{ inputs.allow-net != false && format('--allow-net={0}', inputs.allow-net) || '--deny-net' }}
        ${{ inputs.allow-env != false && format('--allow-env={0}', inputs.allow-env) || '--deny-env' }}
        main.ts
