name: "dts-sample-action"
author: "chaya2z"
description: "Sample GitHub Action with Deno"
inputs:
  token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
    required: false
  allow-net:
    description: |
      Allow network access
      You can specify a comma-separated list
    required: false
  allow-env:
    description: |
      Allow environment variables access
      You can specify a comma-separated list
    required: false
runs:
  using: composite
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - shell: bash
      run: |
        ecno ${{ inputs.allow-net }}
        ecno ${{ inputs.allow-env }}
        ecno ${{ inputs.allow-env != false }}
